name: Build Mac Installer

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build webpack
        run: npx webpack --mode production
      
      - name: Build Mac app
        run: npx electron-builder --mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Mac installer
        uses: actions/upload-artifact@v3
        with:
          name: Sales_SHINE-Mac
          path: |
            dist/*.dmg
            dist/*.zip
